[package]
name = "doe-control-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
dotenv_codegen = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
shuttle-actix-web = "0.55.0"
shuttle-runtime = "0.55.0"
tokio = "1.26.0"
tracing = "0.1.41"
