name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev libglib-2.0
  build:
    runs-on: ubuntu-latest
    needs: deps
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: PUBLIC_KEY="${{ secrets.PUBLIC_KEY }}" PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" REMOTE_ADDRESS="${{ secrets.REMOTE_ADDRESS }}" cargo build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: PUBLIC_KEY="${{ secrets.PUBLIC_KEY }}" PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" REMOTE_ADDRESS="${{ secrets.REMOTE_ADDRESS }}" cargo test
  clippy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Run clippy
      run: PUBLIC_KEY="${{ secrets.PUBLIC_KEY }}" PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" REMOTE_ADDRESS="${{ secrets.REMOTE_ADDRESS }}" cargo clippy
  shuttle-deploy:
    runs-on: ubuntu-latest
    needs: [build, test, clippy]
    steps:
    - uses: actions/checkout@v4
    - name: Run shuttle login
      working-directory: ./doe-control-server
      run: cargo shuttle login --api-key "${{ secrets.SHUTTLE_API_KEY }}" && PUBLIC_KEY="${{ secrets.PUBLIC_KEY }}" PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" REMOTE_ADDRESS="${{ secrets.REMOTE_ADDRESS }}" cargo shuttle deploy --no-follow --name "${{ secrets.SHUTTLE_PROJECT_ID }}"
