name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./doe-control-server
      run: cargo build
    - name: Run tests
      working-directory: ./doe-control-server
      run: cargo test
    - name: Run clippy
      working-directory: ./doe-control-server
      run: cargo clippy
  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./doe-control-client
      run: cargo build
    - name: Run tests
      working-directory: ./doe-control-client
      run: cargo test
    - name: Run clippy
      working-directory: ./doe-control-client
      run: cargo clippy
  admin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./doe-control-admin
      run: cargo build
    - name: Run tests
      working-directory: ./doe-control-admin
      run: cargo test
    - name: Run clippy
      working-directory: ./doe-control-admin
      run: cargo clippy
